version: 2.1
orbs:
  docker: circleci/docker@1.4.0

jobs:
  job_deploy:
    executor: docker/docker
    steps:
      - add_ssh_keys:
          fingerprints:
            - $SSH_KEY_FINGERPRINT
      - run: ssh -oStrictHostKeyChecking=no $DEPLOYED_USER@$DEPLOYED_SERVER 'cd ~/dienthoai && sh ./deploy.sh'

workflows:
  my-pipeline:
    jobs:
      - job_deploy:
          filters:
            branches:
              only:
                - main
                - develop